exports.validSlotTypes = ['SLOT_TXT', 'SLOT_2_LINE', 'SLOT_LOT', 'SLOT_IMG', 'SLOT_PLAY', 'SLOT_CHIP']
exports.validTemplateKeys = ['type', 'header', 'sctv', 'items', 'autoPlay', 'sctvConfig', 'itemsConfig', 'itemSource', 'cssRefs']
exports.validItemsConfigKeys = ['s', 'sp', 'tp', 'ep', 'bp', 'wp', 'w2hr', 'c']
exports.validTemplateTypes = ['SctvTemplate', 'VideoTemplate']
exports.SLOT_TXT = 'SLOT_TXT'
exports.SLOT_2_LINE = 'SLOT_2_LINE'
exports.SLOT_LOT = 'SLOT_LOT'
exports.SLOT_IMG = 'SLOT_IMG'
exports.SLOT_PLAY = 'SLOT_PLAY'
exports.SLOT_CHIP = 'SLOT_CHIP'
exports.HEAD = 'HEAD'
exports.ITEM_STACK = 'ITEM_STACK'
exports.ITEM_CARD = 'ITEM_CARD'
exports.WebCardNavigation = 'webCardNav'
exports.validColors = ['primary', 'secondary', 'systemBg', 'secondaryBg', 'tertiaryBg', 'separator', 'link', 'overlaySc', 'selectionOverlay', 'error', 'success', 'transparent']
exports.validTextStyle = ['heading', 'subHeader', 'title', 'body', 'bodyBold', 'subhead', 'subheadBold', 'footnote', 'footnoteBold', 'caption', 'captionBold']
exports.GENERIC_V2 = "generic_v2"
exports.widgetCriticalField = ['template', 'dataSource']
exports.validHeaderObjectKeys = ['type', 'dataRef', 'left', 'right', 'cActionRef', 'cssRefs']
exports.validTextObjectKeys = ['dataRef', 'style', 'color', 'rd', 'ld', 'cActionRef', 'cssRefs']
exports.validDrawableKeys = ['dataRef', 'cssRefs']
exports.validPlayableObjectKeys = ['gifRef', 'thumbRef', 'videoRef']
exports.validChipObjectKeys = ['imageRef', 's', 'b', 'textRef', 'color', 'style', 'cssRefs', 'cActionRef']
exports.validImageObjectKeys = ['dataRef', 'cssRefs', 'cActionRef']

exports.validTwoLineTextSlotKeys = ['type', 'top', 'bottom', 'cssRefs']
exports.validPlaySlotKeys = ['type', 'playable']
exports.validChipSlotKeys = ['type', 'chip']
exports.validTextSlotKeys = ['type', 'text']
exports.validLottieSlotKeys = ['type', 'lottie']
exports.validImageSlotKeys = ['type', 'image']
